name: Release
on:
  # manual trigger
  workflow_dispatch:

jobs:
  deploy:
    name: release
    runs-on:
      group: npm-deploy
    environment:
      name: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: bullfrogsec/bullfrog@1831f79cce8ad602eef14d2163873f27081ebfb3 # v0.8.4

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          scope: "@uniswap"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npx hardhat compile

      - name: Install npm
        run: npm install -g npm@latest

      - name: Release
        run: |
          npm publish --access public
